// Urdu translations (English UI string -> Urdu). Unknown strings stay English.
// Terms follow everyday Pakistani pharmacy speech: پتہ (strip), ڈبی (box), ادھار (credit), ایکسپائری (expiry), نسخہ (prescription).
export const UR = {
  // ---- navigation / sections ----
  "Home": "ہوم",
  "Daily work": "روزانہ کا کام",
  "Medicines": "ادویات",
  "Parties": "پارٹیاں",
  "Accounts": "حسابات",
  "Administration": "انتظام",
  "New Sale": "نئی فروخت",
  "New sale": "نئی فروخت",
  "Sales": "فروخت",
  "Purchases": "خریداری",
  "Returns": "واپسیاں",
  "Stock": "اسٹاک",
  "Expiry": "ایکسپائری",
  "Order list": "آرڈر لسٹ",
  "Batch trace": "بیچ ٹریس",
  "Rx register": "نسخہ رجسٹر",
  "Customers": "گاہک",
  "Suppliers": "سپلائر",
  "Cash Book & Payments": "کیش بک اور ادائیگیاں",
  "Cash book": "کیش بک",
  "Cash Book": "کیش بک",
  "Reports": "رپورٹس",
  "Backup & Restore": "بیک اپ اور بحالی",
  "Settings": "سیٹنگز",
  "Menu": "مینو",
  "More": "مزید",
  "Sell": "بیچیں",
  "Buy": "خریدیں",
  "New Purchase": "نئی خریداری",
  "New purchase": "نئی خریداری",
  "Log out": "لاگ آؤٹ",
  "Install app": "ایپ انسٹال کریں",
  "App installed": "ایپ انسٹال ہو گئی",
  "Online": "آن لائن",
  "Offline": "آف لائن",
  "Offline — connect to the internet to sign in": "آف لائن — لاگ اِن کے لیے انٹرنیٹ سے جڑیں",

  // ---- login ----
  "Run your pharmacy": "اپنی فارمیسی چلائیں",
  "with confidence.": "اعتماد کے ساتھ۔",
  "Sell, buy, track every batch and expiry date, and never run out of medicine. Made for Pakistani pharmacies. Works even without internet.": "بیچیں، خریدیں، ہر بیچ اور ایکسپائری تاریخ کا حساب رکھیں، اور دوا کبھی ختم نہ ہو۔ پاکستانی فارمیسیوں کے لیے بنائی گئی۔ انٹرنیٹ کے بغیر بھی چلتی ہے۔",
  "Batch & expiry": "بیچ اور ایکسپائری",
  "Demand list": "ضرورت کی فہرست",
  "Works offline": "آف لائن چلتی ہے",
  "Urdu receipts": "اردو رسید",
  "Welcome back": "خوش آمدید",
  "Sign in to your pharmacy to continue": "جاری رکھنے کے لیے اپنی فارمیسی میں لاگ اِن کریں",
  "Username": "یوزر نیم",
  "Password": "پاس ورڈ",
  "Sign in": "لاگ اِن",
  "Signing in…": "لاگ اِن ہو رہا ہے…",
  "Internet is needed to sign in. After that the app works offline.": "لاگ اِن کے لیے انٹرنیٹ چاہیے۔ اس کے بعد ایپ آف لائن بھی چلتی ہے۔",
  "Language / زبان": "زبان / Language",
  "Your session has expired. Please sign in again.": "آپ کا سیشن ختم ہو گیا ہے۔ دوبارہ لاگ اِن کریں۔",
  "Your session has expired. Connect to the internet and sign in again.": "آپ کا سیشن ختم ہو گیا ہے۔ انٹرنیٹ سے جڑیں اور دوبارہ لاگ اِن کریں۔",
  "Log out of this device? Your data stays on this device, but signing in again requires an internet connection.": "اس ڈیوائس سے لاگ آؤٹ کریں؟ آپ کا ڈیٹا اسی ڈیوائس پر رہے گا، مگر دوبارہ لاگ اِن کے لیے انٹرنیٹ چاہیے۔",
  "Required libraries failed to load. Connect to the internet once so the app can be cached for offline use.": "ضروری فائلیں لوڈ نہیں ہوئیں۔ ایک بار انٹرنیٹ سے جڑیں تاکہ ایپ آف لائن استعمال کے لیے محفوظ ہو جائے۔",
  "You do not have permission to open this page.": "آپ کو یہ صفحہ کھولنے کی اجازت نہیں۔",

  // ---- home / dashboard ----
  "Today's sales": "آج کی فروخت",
  "invoices": "بل",
  "Invoices": "بل",
  "Profit": "منافع",
  "In": "آمد",
  "Out": "اخراج",
  "Needs your attention": "توجہ طلب",
  "Expired": "ایکسپائر",
  "Nothing expired": "کوئی ایکسپائر نہیں",
  "Expiring in 30 days": "30 دن میں ایکسپائر",
  "All good": "سب ٹھیک",
  "Low / out of stock": "کم / ختم اسٹاک",
  "Tap to see the list": "فہرست دیکھیں",
  "Stock levels are fine": "اسٹاک ٹھیک ہے",
  "Nothing to order": "کچھ منگوانا نہیں",
  "Items to order": "منگوانے والی ادویات",
  "Loss": "نقصان",
  "at cost": "لاگت پر",
  "What do you want to do?": "آپ کیا کرنا چاہتے ہیں؟",
  "active items": "فعال اشیاء",
  "today": "آج",
  "Sale & purchase returns": "فروخت اور خریداری کی واپسی",
  "Receipts & payments": "وصولی اور ادائیگی",
  "Sales, stock, expiry, profit": "فروخت، اسٹاک، ایکسپائری، منافع",
  "Shop, printer, language": "دکان، پرنٹر، زبان",
  "Overview": "خلاصہ",
  "Udhaar (receivable)": "ادھار (وصولی)",
  "Payables": "ادائیگیاں (سپلائر)",
  "Stock value": "اسٹاک کی قیمت",
  "Cash & bank": "نقد اور بینک",
  "Sales — last 7 days": "فروخت — پچھلے 7 دن",
  "Total": "کل",
  "Report": "رپورٹ",
  "Show as table": "جدول میں دیکھیں",
  "Date": "تاریخ",
  "Top medicines": "زیادہ بکنے والی ادویات",
  "By sales amount, last 7 days": "فروخت کی رقم کے مطابق، پچھلے 7 دن",
  "No sales in the last 7 days": "پچھلے 7 دن میں کوئی فروخت نہیں",
  "Expiring soon": "جلد ایکسپائر ہونے والی",
  "View all": "سب دیکھیں",
  "Batch": "بیچ",
  "Nothing is expiring in the next 3 months": "اگلے 3 مہینوں میں کچھ ایکسپائر نہیں ہو رہا",
  "Recent sales": "حالیہ فروخت",
  "Credit": "ادھار",
  "Paid": "ادا شدہ",
  "No sales yet today": "آج ابھی کوئی فروخت نہیں",
  "You are offline. Everything you do is saved on this device.": "آپ آف لائن ہیں۔ آپ جو بھی کریں گے اس ڈیوائس پر محفوظ ہو گا۔",
  "No backup has been made on this device yet.": "اس ڈیوائس پر ابھی تک بیک اپ نہیں بنا۔",
  "Last backup was": "آخری بیک اپ",
  "days ago": "دن پہلے",
  "Your data only lives on this device.": "آپ کا ڈیٹا صرف اسی ڈیوائس پر ہے۔",
  "Back up": "بیک اپ بنائیں",
  "Customers": "گاہک",

  // ---- POS ----
  "Filter medicines…": "ادویات فلٹر کریں…",
  "Type medicine name, salt or scan barcode": "دوا کا نام، سالٹ لکھیں یا بارکوڈ اسکین کریں",
  "Scan with camera": "کیمرے سے اسکین کریں",
  "Browse medicines": "ادویات دیکھیں",
  "Held sales": "روکی ہوئی فروخت",
  "Hold this sale": "یہ فروخت روک لیں",
  "Use wholesale prices": "ہول سیل قیمتیں استعمال کریں",
  "Use retail prices": "عام قیمتیں استعمال کریں",
  "Continuous scan": "مسلسل اسکین",
  "Add new medicine": "نئی دوا شامل کریں",
  "Customer asked — not available": "گاہک نے مانگی — موجود نہیں",
  "Cancel editing": "ترمیم منسوخ کریں",
  "Clear cart": "کارٹ خالی کریں",
  "Editing": "ترمیم",
  "Edit": "ترمیم",
  "Pay": "ادائیگی",
  "Save": "محفوظ کریں",
  "The cart is empty. Search or scan a medicine to start.": "کارٹ خالی ہے۔ شروع کرنے کے لیے دوا تلاش یا اسکین کریں۔",
  "No medicines yet. Search or scan to add purchased items.": "ابھی کوئی دوا نہیں۔ خریدی ہوئی دوا تلاش یا اسکین کر کے شامل کریں۔",
  "Walk-in Customer": "عام گاہک",
  "Select supplier": "سپلائر منتخب کریں",
  "No supplier (cash purchase)": "کوئی سپلائر نہیں (نقد خریداری)",
  "item(s)": "آئٹم",
  "Disc": "رعایت",
  "disc": "رعایت",
  "discount": "رعایت",
  "Discount": "رعایت",
  "Tax": "ٹیکس",
  "tax": "ٹیکس",
  "Only": "صرف",
  "available for": "دستیاب برائے",
  "Alternatives": "متبادل",
  "Alternatives for": "متبادل برائے",
  "bonus": "بونس",
  "Tap to enter batch & expiry": "بیچ اور ایکسپائری لکھنے کے لیے دبائیں",
  "Out of stock": "اسٹاک ختم",
  "out of stock": "اسٹاک ختم",
  "only expired stock is left": "صرف ایکسپائر مال بچا ہے",
  "No medicine found for": "کوئی دوا نہیں ملی برائے",
  "No medicine matches": "کوئی دوا نہیں ملتی",
  "is inactive": "غیر فعال ہے",
  "keep in fridge": "فریج میں رکھیں",
  "enter the price": "قیمت لکھیں",
  "Added": "شامل ہو گئی",
  "Quantity": "مقدار",
  "Unit": "یونٹ",
  "Price per unit": "فی یونٹ قیمت",
  "Cost per unit": "فی یونٹ لاگت",
  "Discount (Rs)": "رعایت (روپے)",
  "Automatic (earliest expiry first)": "خودکار (پہلے ایکسپائر ہونے والی پہلے)",
  "Directions for patient": "مریض کے لیے ہدایات",
  "e.g. 1+0+1 after meal": "مثلاً صبح شام کھانے کے بعد",
  "Batch no.": "بیچ نمبر",
  "Expiry (MM/YY)": "ایکسپائری (ماہ/سال)",
  "Bonus (free) quantity": "بونس (مفت) مقدار",
  "per pack": "فی پیک",
  "Remove item": "آئٹم ہٹائیں",
  "Update": "اپ ڈیٹ",
  "Add": "شامل کریں",
  "Quantity must be greater than zero.": "مقدار صفر سے زیادہ ہونی چاہیے۔",
  "Rate cannot be negative.": "ریٹ منفی نہیں ہو سکتا۔",
  "Discount must be between 0 and the line amount.": "رعایت صفر اور لائن کی رقم کے درمیان ہونی چاہیے۔",
  "Enter the batch number (printed on the pack).": "بیچ نمبر لکھیں (پیک پر چھپا ہوتا ہے)۔",
  "Enter the expiry date as month/year, for example 05/27.": "ایکسپائری تاریخ ماہ/سال لکھیں، مثلاً 05/27۔",
  "This batch is already expired.": "یہ بیچ پہلے ہی ایکسپائر ہو چکا ہے۔",
  "Enter batch number and expiry for every medicine.": "ہر دوا کا بیچ نمبر اور ایکسپائری لکھیں۔",
  "not enough in-date stock. Reduce the quantity or remove it.": "کافی ان ڈیٹ اسٹاک نہیں۔ مقدار کم کریں یا ہٹا دیں۔",
  "Please fix invalid quantities/rates in the cart.": "کارٹ میں غلط مقدار یا ریٹ درست کریں۔",
  "Payment": "ادائیگی",
  "Save purchase": "خریداری محفوظ کریں",
  "Amount due": "واجب الادا رقم",
  "Controlled medicine — prescription details are required": "کنٹرولڈ دوا — نسخے کی تفصیل ضروری ہے",
  "Prescription details": "نسخے کی تفصیل",
  "Patient name": "مریض کا نام",
  "Doctor name": "ڈاکٹر کا نام",
  "Patient phone": "مریض کا فون",
  "Prescription no. / note": "نسخہ نمبر / نوٹ",
  "Bill discount": "بل پر رعایت",
  "Pay via": "ادائیگی کا طریقہ",
  "off": "کم",
  "No discount": "رعایت نہیں",
  "Amount received": "وصول شدہ رقم",
  "Amount paid": "ادا کی گئی رقم",
  "Supplier invoice no.": "سپلائر بل نمبر",
  "Note": "نوٹ",
  "Print receipt": "رسید پرنٹ کریں",
  "Back": "واپس",
  "Complete sale": "فروخت مکمل کریں",
  "Subtotal": "ذیلی کل",
  "Discount cannot exceed the subtotal.": "رعایت ذیلی کل سے زیادہ نہیں ہو سکتی۔",
  "Change": "باقی رقم",
  "Paid amount exceeds total": "ادا کی گئی رقم کل سے زیادہ ہے",
  "Fully paid": "مکمل ادا",
  "Balance due (udhaar)": "بقایا (ادھار)",
  "Payable": "قابلِ ادائیگی",
  "added to customer account": "گاہک کے کھاتے میں شامل",
  "added to supplier account": "سپلائر کے کھاتے میں شامل",
  "Short by": "کمی",
  "Select a customer for credit (udhaar).": "ادھار کے لیے گاہک منتخب کریں۔",
  "Select a supplier for credit.": "ادھار کے لیے سپلائر منتخب کریں۔",
  "Exact": "ٹھیک رقم",
  "Udhaar (credit)": "ادھار",
  "Unpaid": "غیر ادا",
  "Saving…": "محفوظ ہو رہا ہے…",
  "updated": "اپ ڈیٹ ہو گیا",
  "was already saved": "پہلے ہی محفوظ تھا",
  "Sale completed": "فروخت مکمل",
  "Purchase saved": "خریداری محفوظ",
  "Print": "پرنٹ",
  "View": "دیکھیں",
  "Cart is empty": "کارٹ خالی ہے",
  "Sale": "فروخت",
  "Sale held": "فروخت روک لی گئی",
  "No held sales": "کوئی روکی ہوئی فروخت نہیں",
  "Replace the current cart with the held sale? (Hold the current cart first if you need it.)": "موجودہ کارٹ کی جگہ روکی ہوئی فروخت لائیں؟ (ضرورت ہو تو پہلے موجودہ کارٹ روک لیں۔)",
  "You do not have permission to add medicines": "آپ کو دوا شامل کرنے کی اجازت نہیں",
  "Discard changes to this document?": "اس دستاویز کی تبدیلیاں رد کریں؟",
  "Clear all items from the cart?": "کارٹ سے تمام آئٹم ہٹا دیں؟",
  "Clear": "صاف کریں",
  "Using wholesale prices for new items": "نئے آئٹمز کے لیے ہول سیل قیمتیں",
  "Using retail prices for new items": "نئے آئٹمز کے لیے عام قیمتیں",

  // ---- medicines ----
  "Add medicine": "دوا شامل کریں",
  "Edit medicine": "دوا میں ترمیم",
  "New medicine": "نئی دوا",
  "Medicine name": "دوا کا نام",
  "e.g. Panadol": "مثلاً پیناڈول",
  "Strength": "طاقت",
  "Type": "قسم",
  "Generic / salt name": "جینرک / سالٹ کا نام",
  "e.g. Paracetamol": "مثلاً پیراسیٹامول",
  "Used to find other brands of the same medicine.": "اسی دوا کے دوسرے برانڈ ڈھونڈنے کے لیے۔",
  "Company": "کمپنی",
  "e.g. GSK": "مثلاً GSK",
  "Prices are for ONE PACK (one strip / bottle / box as you buy it).": "قیمتیں ایک پیک کی ہیں (ایک پتہ / بوتل / ڈبی جیسے آپ خریدتے ہیں)۔",
  "Sale price": "فروخت قیمت",
  "same as MRP": "MRP کے برابر",
  "Cost price": "لاگت قیمت",
  "Pack": "پیک",
  "Sold as": "بکتی ہے بطور",
  "Units in one pack": "ایک پیک میں تعداد",
  "Unit name": "یونٹ کا نام",
  "Also sell single units (loose tablets)": "کھلی گولیاں بھی بیچیں",
  "Price of one unit (optional)": "ایک گولی کی قیمت (اختیاری)",
  "Packs in one box (for purchasing)": "ایک ڈبی میں پیک (خریداری کے لیے)",
  "Medicine class": "دوا کی قسم",
  "Controlled medicines always ask for the patient and doctor name when sold.": "کنٹرولڈ ادویات بیچتے وقت ہمیشہ مریض اور ڈاکٹر کا نام پوچھا جاتا ہے۔",
  "Storage": "ذخیرہ",
  "Tell me when packs fall below": "جب پیک اتنے سے کم ہوں تو بتائیں",
  "Rack / shelf": "ریک / شیلف",
  "Group": "گروپ",
  "Groups": "گروپس",
  "Stock you already have (optional)": "جو اسٹاک آپ کے پاس پہلے سے ہے (اختیاری)",
  "Packs": "پیک",
  "You can add more batches later from Stock.": "مزید بیچ بعد میں اسٹاک سے شامل کر سکتے ہیں۔",
  "More details": "مزید تفصیل",
  "Urdu name": "اردو نام",
  "Usual directions (printed on receipt)": "عام ہدایات (رسید پر چھپیں گی)",
  "Code": "کوڈ",
  "Wholesale price": "ہول سیل قیمت",
  "Barcode": "بارکوڈ",
  "Scan": "اسکین",
  "Generate": "بنائیں",
  "Track stock (turn off for services)": "اسٹاک کا حساب (سروس کے لیے بند کریں)",
  "Photo": "تصویر",
  "Active (available for sale)": "فعال (فروخت کے لیے)",
  "Enter the medicine name.": "دوا کا نام لکھیں۔",
  "Enter the MRP (price on the pack).": "MRP لکھیں (پیک پر چھپی قیمت)۔",
  "To add stock now, fill the batch number, expiry date (MM/YY) and packs.": "ابھی اسٹاک شامل کرنے کے لیے بیچ نمبر، ایکسپائری (ماہ/سال) اور پیک لکھیں۔",
  "Medicine saved, but the stock was not added": "دوا محفوظ ہو گئی مگر اسٹاک شامل نہیں ہوا",
  "Medicine updated": "دوا اپ ڈیٹ ہو گئی",
  "Medicine added": "دوا شامل ہو گئی",
  "medicine(s)": "دوا",
  "No groups yet": "ابھی کوئی گروپ نہیں",
  "New group name (e.g. Baby care)": "نئے گروپ کا نام (مثلاً بچوں کی دیکھ بھال)",
  "Group name": "گروپ کا نام",
  "Search name, salt, company, barcode…": "نام، سالٹ، کمپنی، بارکوڈ تلاش کریں…",
  "All": "سب",
  "Low stock": "کم اسٹاک",
  "Rx": "نسخہ",
  "Controlled": "کنٹرولڈ",
  "Fridge": "فریج",
  "No price": "قیمت نہیں",
  "Inactive": "غیر فعال",
  "No medicines found": "کوئی دوا نہیں ملی",
  "Add popular Pakistani medicines": "مشہور پاکستانی ادویات شامل کریں",
  "Add medicines": "ادویات شامل کریں",
  "No medicine with barcode": "اس بارکوڈ کی کوئی دوا نہیں",
  "Add a new medicine?": "نئی دوا شامل کریں؟",
  "No medicine found": "کوئی دوا نہیں ملی",
  "Margin": "مارجن",
  "Batches in stock": "اسٹاک میں بیچ",
  "Other brands (same salt)": "دوسرے برانڈ (وہی سالٹ)",
  "Add to order list": "آرڈر لسٹ میں شامل کریں",
  "Stock history": "اسٹاک کی تاریخ",
  "Add / adjust stock": "اسٹاک شامل / درست کریں",
  "Delete": "حذف کریں",
  "Medicines with transactions are deactivated instead.": "جن ادویات کا لین دین ہو چکا وہ حذف کی بجائے غیر فعال ہوں گی۔",
  "Medicine deleted": "دوا حذف ہو گئی",
  "Medicine deactivated (has transactions)": "دوا غیر فعال (لین دین موجود ہے)",
  "Generic / salt": "جینرک / سالٹ",
  "No other brand with this generic name": "اس سالٹ کا کوئی اور برانڈ نہیں",
  "Add the generic name to this medicine to find alternatives": "متبادل ڈھونڈنے کے لیے اس دوا میں سالٹ کا نام لکھیں",
  "Add the generic name": "سالٹ کا نام لکھیں",
  "This adds about": "یہ شامل کرے گا تقریباً",
  "common medicines and supplies to your list so you do not have to type them.": "عام ادویات اور سامان آپ کی فہرست میں تاکہ آپ کو لکھنا نہ پڑے۔",
  "Medicines you already have are not duplicated.": "جو ادویات پہلے سے موجود ہیں دوبارہ شامل نہیں ہوں گی۔",
  "No prices and no stock are added. The MRP is filled in automatically the first time you enter a purchase.": "قیمت اور اسٹاک شامل نہیں ہوتا۔ پہلی خریداری لکھتے وقت MRP خود بھر جاتا ہے۔",
  "Pack sizes are typical — correct any that differ from your packs.": "پیک سائز عام ہیں — جو آپ کے پیک سے مختلف ہوں درست کر لیں۔",
  "Adding medicines…": "ادویات شامل ہو رہی ہیں…",
  "medicines added": "ادویات شامل ہوئیں",
  "already existed": "پہلے سے موجود تھیں",

  // ---- medicine types / packs / classes ----
  "Tablet": "گولی",
  "Capsule": "کیپسول",
  "Syrup": "شربت",
  "Suspension": "سسپنشن",
  "Injection": "ٹیکہ",
  "Drip / IV": "ڈرپ",
  "Cream": "کریم",
  "Ointment": "مرہم",
  "Gel": "جیل",
  "Drops": "قطرے",
  "Inhaler": "انہیلر",
  "Sachet": "ساشے",
  "Powder": "پاؤڈر",
  "Lotion": "لوشن",
  "Spray": "اسپرے",
  "Suppository": "سپوزیٹری",
  "Surgical": "سرجیکل",
  "Other": "دیگر",
  "Strip": "پتہ",
  "Box": "ڈبی",
  "Bottle": "بوتل",
  "Ampoule": "ایمپول",
  "Vial": "ویال",
  "Tube": "ٹیوب",
  "Packet": "پیکٹ",
  "Tin": "ٹن",
  "Jar": "جار",
  "Piece": "عدد",
  "Pair": "جوڑی",
  "ml": "ملی لیٹر",
  "OTC (no prescription)": "OTC (بغیر نسخہ)",
  "Prescription (Rx)": "نسخے والی (Rx)",
  "Controlled / Narcotic": "کنٹرولڈ / نشہ آور",
  "General item (non-medicine)": "عام چیز (دوا نہیں)",
  "OTC": "OTC",
  "General": "عام",
  "Room temperature": "عام درجہ حرارت",
  "Cool place (below 25°C)": "ٹھنڈی جگہ (25°C سے کم)",
  "Fridge (2–8°C)": "فریج (2–8°C)",
  "Service": "سروس",
  "Fridge items": "فریج کی اشیاء",

  // ---- stock ----
  "Adjustments": "درستیاں",
  "Add / adjust": "شامل / درست",
  "Search medicine, salt, company…": "دوا، سالٹ، کمپنی تلاش کریں…",
  "All stock": "تمام اسٹاک",
  "In stock": "اسٹاک میں",
  "No medicines match": "کوئی دوا نہیں ملتی",
  "Min": "کم از کم",
  "batches": "بیچ",
  "Stock value (cost)": "اسٹاک کی قیمت (لاگت)",
  "Retail value": "فروخت کی قیمت",
  "Medicine not found": "دوا نہیں ملی",
  "Current stock": "موجودہ اسٹاک",
  "Not tracked": "حساب نہیں",
  "Reference": "حوالہ",
  "Balance": "بقایا",
  "Opening": "ابتدائی",
  "Totals / closing": "کل / اختتامی",
  "No movements in this period": "اس مدت میں کوئی حرکت نہیں",
  "Opening stock": "ابتدائی اسٹاک",
  "Purchase": "خریداری",
  "Sale return": "فروخت کی واپسی",
  "Purchase return": "خریداری کی واپسی",
  "Adjustment": "درستی",
  "Stock count correction": "اسٹاک گنتی کی درستی",
  "Damaged": "ٹوٹا پھوٹا",
  "Lost / theft": "گم / چوری",
  "Stock in (other)": "اسٹاک آمد (دیگر)",
  "To receive new stock from a supplier use New Purchase (it records the supplier bill). Use this page for opening stock, damaged or expired medicines and stock counts.": "سپلائر سے نیا مال لینے کے لیے نئی خریداری استعمال کریں (اس میں سپلائر کا بل لکھا جاتا ہے)۔ یہ صفحہ ابتدائی اسٹاک، خراب یا ایکسپائر ادویات اور اسٹاک گنتی کے لیے ہے۔",
  "Search medicine to add…": "شامل کرنے کے لیے دوا تلاش کریں…",
  "Reason": "وجہ",
  "Save adjustment": "درستی محفوظ کریں",
  "New batch": "نیا بیچ",
  "Add (+)": "شامل (+)",
  "Remove (−)": "کم (−)",
  "Set count": "گنتی مقرر کریں",
  "Qty": "تعداد",
  "Search a medicine to adjust its stock": "اسٹاک درست کرنے کے لیے دوا تلاش کریں",
  "This item does not track stock": "اس آئٹم کا اسٹاک حساب نہیں",
  "No medicine for": "کوئی دوا نہیں برائے",
  "No match": "کوئی نتیجہ نہیں",
  "Enter a valid quantity for": "درست مقدار لکھیں برائے",
  "Enter batch number and expiry (MM/YY) for the new batch of": "نئے بیچ کا بیچ نمبر اور ایکسپائری (ماہ/سال) لکھیں برائے",
  "saved": "محفوظ ہو گیا",
  "Stock adjustments": "اسٹاک درستیاں",
  "New": "نیا",
  "No adjustments in this period": "اس مدت میں کوئی درستی نہیں",
  "Not found": "نہیں ملا",
  "Voided": "منسوخ شدہ",
  "by": "از",
  "By": "از",
  "Before": "پہلے",
  "Value": "قدر",
  "Stock changes will be reversed.": "اسٹاک کی تبدیلیاں واپس ہو جائیں گی۔",
  "Adjustment voided": "درستی منسوخ ہو گئی",

  // ---- expiry ----
  "30 days": "30 دن",
  "31–60 days": "31–60 دن",
  "61–90 days": "61–90 دن",
  "3–6 months": "3–6 مہینے",
  "All batches": "تمام بیچ",
  "Return list": "واپسی کی فہرست",
  "Search medicine or batch…": "دوا یا بیچ تلاش کریں…",
  "Value at cost": "لاگت پر قیمت",
  "days left": "دن باقی",
  "Return to supplier": "سپلائر کو واپس کریں",
  "Write off (destroy)": "ضائع کریں (تلف)",
  "Write off": "ضائع کریں",
  "of": "کا",
  "Loss at cost": "لاگت پر نقصان",
  "Written off": "ضائع کر دیا گیا",
  "No expired medicines. Well done!": "کوئی ایکسپائر دوا نہیں۔ شاباش!",
  "Nothing in this period": "اس مدت میں کچھ نہیں",
  "Expiry return list": "ایکسپائری واپسی کی فہرست",
  "Exp": "ایکس",
  "Total value": "کل قیمت",
  "Unknown supplier": "نامعلوم سپلائر",
  "Expiry": "ایکسپائری",
  "Medicine": "دوا",
  "Send on WhatsApp": "واٹس ایپ پر بھیجیں",
  "Copy": "کاپی",
  "Copied": "کاپی ہو گیا",
  "Could not copy": "کاپی نہیں ہو سکا",
  "Nothing to return": "واپس کرنے کو کچھ نہیں",
  "This batch was not bought through a purchase bill, so it cannot be returned to a supplier. Use Write off instead.": "یہ بیچ خریداری بل سے نہیں آیا اس لیے سپلائر کو واپس نہیں ہو سکتا۔ ضائع کرنے کا آپشن استعمال کریں۔",
  "The purchase bill of this batch was not found.": "اس بیچ کا خریداری بل نہیں ملا۔",

  // ---- order list ----
  "Add medicine to order list": "آرڈر لسٹ میں دوا شامل کریں",
  "Search medicine…": "دوا تلاش کریں…",
  "Not in my list — type the name": "میری فہرست میں نہیں — نام لکھیں",
  "Running low — suggested": "کم ہو رہی ہیں — تجویز",
  "Add all": "سب شامل کریں",
  "To order": "منگوانی ہیں",
  "Supplier not decided": "سپلائر طے نہیں",
  "Supplier": "سپلائر",
  "Not decided": "طے نہیں",
  "Customer asked": "گاہک نے مانگی",
  "Manual": "ہاتھ سے",
  "Mark as ordered": "آرڈر ہو گیا لکھیں",
  "Marked as ordered": "آرڈر ہو گیا",
  "Receive (new purchase)": "وصول کریں (نئی خریداری)",
  "Your order list is empty": "آپ کی آرڈر لسٹ خالی ہے",
  "Ordered — waiting for delivery": "آرڈر ہو چکا — مال کا انتظار",
  "Make a list of what to buy, send it to your supplier on WhatsApp, and receive it with New Purchase. The list updates itself when stock runs low or a customer asks for something you do not have.": "کیا خریدنا ہے اس کی فہرست بنائیں، سپلائر کو واٹس ایپ پر بھیجیں، اور مال آنے پر نئی خریداری میں وصول کریں۔ اسٹاک کم ہونے یا گاہک کے مانگنے پر فہرست خود بڑھ جاتی ہے۔",
  "Order": "آرڈر",
  "Thank you": "شکریہ",
  "Added to order list": "آرڈر لسٹ میں شامل ہو گیا",
  "How many to order?": "کتنی منگوانی ہیں؟",
  "How many packs?": "کتنے پیک؟",
  "e.g. customer will come tomorrow": "مثلاً گاہک کل آئے گا",
  "These items are not in your medicine list yet. Add them first.": "یہ آئٹمز آپ کی دوا فہرست میں نہیں۔ پہلے انہیں شامل کریں۔",
  "Low stock / reorder": "کم اسٹاک / دوبارہ آرڈر",

  // ---- trace ----
  "Type a medicine name or a batch number. You will see the supplier it came from and every customer who bought it — useful when a company recalls a batch.": "دوا کا نام یا بیچ نمبر لکھیں۔ آپ دیکھ سکیں گے کہ مال کس سپلائر سے آیا اور کن کن گاہکوں نے خریدا — جب کمپنی کوئی بیچ واپس منگوائے تو کام آتا ہے۔",
  "Medicine name or batch number": "دوا کا نام یا بیچ نمبر",
  "No batch found": "کوئی بیچ نہیں ملا",
  "Search to begin": "شروع کرنے کے لیے تلاش کریں",
  "left": "باقی",
  "sold out": "ختم ہو گیا",
  "Batch not found": "بیچ نہیں ملا",
  "Recall list": "ریکال فہرست",
  "Purchase bill": "خریداری بل",
  "Received on": "وصول ہوا",
  "Received": "وصول شدہ",
  "Sold": "فروخت شدہ",
  "Returned by customers": "گاہکوں نے واپس کیا",
  "Removed / written off": "ہٹایا / ضائع کیا",
  "Remaining": "باقی",
  "Write off remaining": "باقی ضائع کریں",
  "Sold to": "فروخت کی گئی",
  "Invoice": "بل",
  "Customer": "گاہک",
  "Phone": "فون",
  "Not sold yet": "ابھی فروخت نہیں ہوا",
  "Batch recall list": "بیچ ریکال فہرست",
  "Opening stock ": "ابتدائی اسٹاک",
  "Cost": "لاگت",

  // ---- Rx ----
  "A record of every prescription and controlled medicine sold. Keep it ready for the drug inspector.": "فروخت ہونے والی ہر نسخے والی اور کنٹرولڈ دوا کا ریکارڈ۔ اسے ڈرگ انسپکٹر کے لیے تیار رکھیں۔",
  "Show": "دکھائیں",
  "All Rx + controlled": "تمام نسخے + کنٹرولڈ",
  "Controlled only": "صرف کنٹرولڈ",
  "Patient": "مریض",
  "Doctor": "ڈاکٹر",
  "No prescription medicines sold in this period": "اس مدت میں کوئی نسخے والی دوا فروخت نہیں ہوئی",
  "Prescription & controlled drug register": "نسخہ اور کنٹرولڈ ادویات کا رجسٹر",
  "Licence": "لائسنس",
  "Pharmacist": "فارماسسٹ",
  "Prescription": "نسخہ",

  // ---- documents ----
  "Sale": "فروخت",
  "Number or": "نمبر یا",
  "customer": "گاہک",
  "supplier": "سپلائر",
  "Status": "حالت",
  "Unpaid / partial": "غیر ادا / جزوی",
  "Void": "منسوخ",
  "Partial": "جزوی",
  "Documents": "دستاویزات",
  "Due": "واجب",
  "due": "واجب",
  "Search": "تلاش",
  "No sales found for this period": "اس مدت میں کوئی فروخت نہیں",
  "No purchases found for this period": "اس مدت میں کوئی خریداری نہیں",
  "Document not found": "دستاویز نہیں ملی",
  "Return items": "آئٹم واپس کریں",
  "No actions available": "کوئی عمل دستیاب نہیں",
  "Stock and ledger effects were reversed.": "اسٹاک اور کھاتے کے اثرات واپس کر دیے گئے۔",
  "Rate": "ریٹ",
  "Amount": "رقم",
  "Returned": "واپس شدہ",
  "Change given": "دی گئی باقی رقم",
  "Balance due": "بقایا رقم",
  "Entered by": "اندراج کنندہ",
  "Created": "بنایا گیا",
  "Last edited": "آخری ترمیم",
  "Supplier invoice": "سپلائر بل",
  "Void document": "دستاویز منسوخ کریں",
  "Voiding reverses stock (batch by batch) and all ledger entries. The number stays reserved for audit purposes. This cannot be undone.": "منسوخ کرنے سے اسٹاک (بیچ کے حساب سے) اور تمام اندراجات واپس ہو جاتے ہیں۔ نمبر ریکارڈ کے لیے محفوظ رہتا ہے۔ یہ عمل واپس نہیں ہو سکتا۔",
  "Enter a reason.": "وجہ لکھیں۔",
  "voided": "منسوخ ہو گیا",
  "Return": "واپسی",
  "Everything in this document has already been returned.": "اس دستاویز کی ہر چیز پہلے ہی واپس ہو چکی ہے۔",
  "Return all": "سب واپس کریں",
  "returned": "واپس شدہ",
  "max": "زیادہ سے زیادہ",
  "Bought": "خریدا",
  "Return total": "واپسی کا کل",
  "Customer returned": "گاہک نے واپس کی",
  "Wrong medicine given": "غلط دوا دی گئی",
  "Doctor changed prescription": "ڈاکٹر نے نسخہ بدل دیا",
  "Expired / near expiry": "ایکسپائر / ایکسپائری کے قریب",
  "Damaged / broken": "خراب / ٹوٹی ہوئی",
  "Wrong item": "غلط آئٹم",
  "Slow moving": "کم بکنے والی",
  "Refund paid": "واپس کی گئی رقم",
  "Refund received": "وصول شدہ رقم",
  "Refund": "رقم واپسی",
  "Unrefunded amount is adjusted in the customer account.": "جو رقم واپس نہ ہو وہ گاہک کے کھاتے میں ایڈجسٹ ہو گی۔",
  "Unrefunded amount is adjusted in the supplier account.": "جو رقم واپس نہ ہو وہ سپلائر کے کھاتے میں ایڈجسٹ ہو گی۔",
  "Walk-in/cash documents are refunded in full.": "نقد دستاویزات کی مکمل رقم واپس کی جاتی ہے۔",
  "Account": "کھاتا",
  "Save return": "واپسی محفوظ کریں",
  "To create a return, open the original sale or purchase and choose Return items. Expired medicines can be returned to the supplier from the Expiry screen.": "واپسی بنانے کے لیے اصل فروخت یا خریداری کھولیں اور آئٹم واپس کریں چنیں۔ ایکسپائر ادویات ایکسپائری اسکرین سے سپلائر کو واپس ہو سکتی ہیں۔",
  "Sale returns": "فروخت کی واپسیاں",
  "Purchase returns": "خریداری کی واپسیاں",
  "No returns in this period": "اس مدت میں کوئی واپسی نہیں",
  "Return not found": "واپسی نہیں ملی",
  "against": "بمقابلہ",
  "Stock and ledger effects of this return will be reversed.": "اس واپسی کے اسٹاک اور کھاتے کے اثرات واپس ہو جائیں گے۔",
  "Return voided": "واپسی منسوخ ہو گئی",

  // ---- parties / accounts / vouchers ----
  "Customer ledger": "گاہک کا کھاتا",
  "Supplier ledger": "سپلائر کا کھاتا",
  "Account ledger": "کھاتے کی تفصیل",
  "Receivables": "وصولیاں (ادھار)",
  "Total receivable": "کل وصولی",
  "Total payable": "کل ادائیگی",
  "Advances": "ایڈوانس",
  "Advances paid": "ادا کیا ایڈوانس",
  "Name": "نام",
  "Email": "ای میل",
  "Address": "پتہ",
  "Active": "فعال",
  "Receive": "وصول کریں",
  "Receive payment": "ادائیگی وصول کریں",
  "Make payment": "ادائیگی کریں",
  "Statement": "اسٹیٹمنٹ",
  "Ledger": "کھاتا",
  "With balance": "بقایا والے",
  "Details": "تفصیل",
  "Debit (Dr)": "ڈیبٹ (Dr)",
  "Credit (Cr)": "کریڈٹ (Cr)",
  "Ref": "حوالہ",
  "Apply": "لگائیں",
  "remaining": "باقی",
  "No transactions in this period": "اس مدت میں کوئی لین دین نہیں",
  "Opening balance": "ابتدائی بقایا",
  "Closing": "اختتامی",
  "Add": "شامل کریں",
  "Cash in Hand": "نقد رقم",
  "Sales Returns": "فروخت کی واپسیاں",
  "Purchase Returns": "خریداری کی واپسیاں",
  "Sales Tax Payable": "قابلِ ادائیگی سیلز ٹیکس",
  "Opening Balance Equity": "ابتدائی بقایا ایکویٹی",
  "Other Income": "دیگر آمدنی",
  "General Expenses": "عمومی اخراجات",
  "Bank / Wallet": "بینک / والیٹ",
  "Cash": "نقد",
  "Income": "آمدنی",
  "Expense": "اخراجات",
  "Other Asset": "دیگر اثاثہ",
  "Liability": "ذمہ داری",
  "Equity": "ایکویٹی",
  "Cash book entry": "کیش بک اندراج",
  "Money received": "وصول شدہ رقم",
  "Payment made": "کی گئی ادائیگی",
  "Transfer": "منتقلی",
  "Receipt": "رسید",
  "Receipts": "وصولیاں",
  "Payments": "ادائیگیاں",
  "Transfers": "منتقلیاں",
  "Method / Ref": "طریقہ / حوالہ",
  "Voucher": "واؤچر",
  "System": "سسٹم",
  "Owner": "مالک",
  "Counter staff": "کاؤنٹر اسٹاف",

  // ---- reports ----
  "Daily sales": "روزانہ فروخت",
  "Sales by date range": "تاریخ کے حساب سے فروخت",
  "Sales returns": "فروخت کی واپسیاں",
  "Medicine-wise sales": "دوا کے حساب سے فروخت",
  "Company-wise sales": "کمپنی کے حساب سے فروخت",
  "Salt / generic-wise sales": "سالٹ کے حساب سے فروخت",
  "Medicine-wise purchases": "دوا کے حساب سے خریداری",
  "Supplier-wise purchases": "سپلائر کے حساب سے خریداری",
  "Payables": "ادائیگیاں",
  "Daily closing": "روزانہ کلوزنگ",
  "Stock report": "اسٹاک رپورٹ",
  "Batch-wise stock": "بیچ کے حساب سے اسٹاک",
  "Expiry report": "ایکسپائری رپورٹ",
  "Dead stock (not selling)": "ڈیڈ اسٹاک (نہ بکنے والی)",
  "Profit summary": "منافع کا خلاصہ",
  "Inventory": "انوینٹری",
  "Report not available": "رپورٹ دستیاب نہیں",
  "From": "سے",
  "To": "تک",
  "As of": "تاریخ تک",
  "Select…": "منتخب کریں…",
  "Run": "چلائیں",
  "Today": "آج",
  "Month": "مہینہ",
  "Calculating…": "حساب ہو رہا ہے…",
  "No data for the selected filters": "منتخب فلٹر کے لیے کوئی ڈیٹا نہیں",
  "Select a customer to view the ledger": "کھاتا دیکھنے کے لیے گاہک منتخب کریں",
  "Select a supplier to view the ledger": "کھاتا دیکھنے کے لیے سپلائر منتخب کریں",
  "printed": "پرنٹ شدہ",
  "Show medicines expiring within": "اتنے وقت میں ایکسپائر ہونے والی ادویات دکھائیں",
  "Already expired": "پہلے سے ایکسپائر",
  "60 days": "60 دن",
  "3 months": "3 مہینے",
  "6 months": "6 مہینے",
  "1 year": "1 سال",
  "Net qty sold": "خالص فروخت مقدار",
  "Net amount": "خالص رقم",
  "Medicines sold": "فروخت شدہ ادویات",
  "Companies": "کمپنیاں",
  "Brands sold": "فروخت شدہ برانڈ",
  "Salts": "سالٹ",
  "Medicines to order": "منگوانے والی ادویات",
  "Money stuck": "پھنسی ہوئی رقم",
  "Value (cost)": "قدر (لاگت)",
  "Value (sale)": "قدر (فروخت)",
  "Value at MRP": "MRP پر قدر",
  "Value at sale price": "فروخت قیمت پر قدر",
  "MRP value": "MRP قدر",
  "Cost value": "لاگت کی قدر",
  "Time left": "باقی وقت",
  "Last supplier": "آخری سپلائر",
  "In stock ": "اسٹاک میں",
  "Minimum": "کم از کم",
  "Purchased": "خریدا گیا",
  "Bonus (free)": "بونس (مفت)",
  "Bills": "بل",
  "Gross sales": "کل فروخت",
  "Discounts": "رعایتیں",
  "Collected": "وصول شدہ",
  "On credit": "ادھار پر",
  "Cash/bank sales": "نقد/بینک فروخت",
  "Credit sales": "ادھار فروخت",
  "Net sales": "خالص فروخت",
  "Gross profit": "مجموعی منافع",
  "Gross margin": "مجموعی مارجن",
  "Net profit": "خالص منافع",
  "Debits": "ڈیبٹ",
  "Credits": "کریڈٹ",
  "Item": "آئٹم",
  "Items": "آئٹمز",
  "Customer ": "گاہک",
  "Time": "وقت",
  "Pay via ": "ادائیگی",
  "Sales (excl. tax, after discounts)": "فروخت (ٹیکس کے بغیر، رعایت کے بعد)",
  "Less: sales returns": "منفی: فروخت کی واپسی",
  "Less: cost of goods sold": "منفی: فروخت شدہ مال کی لاگت",
  "Add: other income": "جمع: دیگر آمدنی",
  "Less: expenses": "منفی: اخراجات",
  "Less: stock adjustments (loss) / gain": "منفی: اسٹاک درستی (نقصان) / فائدہ",
  "Amounts are line amounts before bill-level discount and tax.": "رقوم بل کی رعایت اور ٹیکس سے پہلے کی ہیں۔",
  "Cost of goods sold uses the purchase price recorded on each sale line at the time of sale.": "فروخت شدہ مال کی لاگت فروخت کے وقت درج خریداری قیمت سے نکالی جاتی ہے۔",
  "Quantities are calculated from stock movements up to the selected date; values use current prices.": "مقداریں منتخب تاریخ تک اسٹاک کی حرکت سے نکالی گئی ہیں؛ قدر موجودہ قیمتوں پر ہے۔",
  "Medicines in stock that were not sold in the selected period.": "اسٹاک میں موجود وہ ادویات جو منتخب مدت میں فروخت نہیں ہوئیں۔",

  // ---- settings ----
  "Pharmacy profile": "فارمیسی کی معلومات",
  "Pharmacy name": "فارمیسی کا نام",
  "Pharmacy name in Urdu": "فارمیسی کا اردو نام",
  "NTN": "این ٹی این",
  "Drug sale licence no.": "ڈرگ سیل لائسنس نمبر",
  "Qualified person / pharmacist": "کوالیفائیڈ پرسن / فارماسسٹ",
  "Receipt footer": "رسید کا فوٹر",
  "Currency": "کرنسی",
  "Pharmacy rules": "فارمیسی کے اصول",
  "Warn about expiry within (days)": "اتنے دن میں ایکسپائری پر خبردار کریں",
  "Order stock for (days of sales)": "اتنے دن کی فروخت کے برابر مال منگوائیں",
  "Ask patient & doctor name for every prescription medicine": "ہر نسخے والی دوا پر مریض اور ڈاکٹر کا نام پوچھیں",
  "Print batch and expiry on the receipt": "رسید پر بیچ اور ایکسپائری چھاپیں",
  "Print dosage directions on the receipt": "رسید پر دوا کھانے کی ہدایات چھاپیں",
  "When a purchase brings a new MRP, change the sale price too": "نئی خریداری میں MRP بدلے تو فروخت قیمت بھی بدل دیں",
  "Update cost price from the latest purchase": "تازہ خریداری سے لاگت قیمت اپ ڈیٹ کریں",
  "Charge sales tax": "سیلز ٹیکس لگائیں",
  "Tax rate (%)": "ٹیکس کی شرح (%)",
  "Tax rate must be between 0 and 100": "ٹیکس کی شرح 0 اور 100 کے درمیان ہونی چاہیے",
  "Document number prefixes (use a different prefix on each device if several devices sell at the same time)": "دستاویز نمبر کے پریفکس (اگر کئی ڈیوائسز پر ایک ساتھ فروخت ہو تو ہر ڈیوائس کا الگ پریفکس رکھیں)",
  "Sale return": "فروخت کی واپسی",
  "Appearance": "ظاہری شکل",
  "Follow device": "ڈیوائس کے مطابق",
  "Light": "روشن",
  "Dark": "تاریک",
  "Receipt printer": "رسید پرنٹر",
  "Print method": "پرنٹ کا طریقہ",
  "Browser print dialog (any printer, PDF, AirPrint)": "براؤزر پرنٹ (کوئی بھی پرنٹر، PDF، AirPrint)",
  "Bluetooth ESC/POS printer (Web Bluetooth, BLE)": "بلوٹوتھ ESC/POS پرنٹر (Web Bluetooth, BLE)",
  "not supported here": "یہاں سپورٹ نہیں",
  "RawBT app (Android, Classic Bluetooth printers)": "RawBT ایپ (اینڈرائیڈ، کلاسک بلوٹوتھ پرنٹر)",
  "Paper width": "کاغذ کی چوڑائی",
  "Copies": "کاپیاں",
  "Print receipt automatically after each sale": "ہر فروخت کے بعد رسید خود پرنٹ کریں",
  "Connect printer": "پرنٹر جوڑیں",
  "Disconnect": "منقطع کریں",
  "Transfer speed": "ٹرانسفر کی رفتار",
  "If receipts come out cut off or garbled, choose Safe.": "اگر رسید کٹی یا خراب نکلے تو Safe چنیں۔",
  "Install the free RawBT app from Google Play, pair your printer in RawBT, then print from here.": "گوگل پلے سے مفت RawBT ایپ انسٹال کریں، اس میں پرنٹر جوڑیں، پھر یہاں سے پرنٹ کریں۔",
  "Urdu printing mode": "اردو پرنٹنگ موڈ",
  "most printers": "اکثر پرنٹر",
  "older printers": "پرانے پرنٹر",
  "Urdu is printed as an image. If Test print shows blank space or garbage where Urdu should be, switch to Compatibility.": "اردو تصویر کی شکل میں چھپتی ہے۔ اگر ٹیسٹ پرنٹ میں اردو کی جگہ خالی یا خراب نکلے تو Compatibility چنیں۔",
  "Test print (incl. Urdu)": "ٹیسٹ پرنٹ (اردو سمیت)",
  "Connected": "جڑا ہوا",
  "Not connected": "جڑا نہیں",
  "No printer connected": "کوئی پرنٹر نہیں جڑا",
  "My account": "میرا اکاؤنٹ",
  "Session valid until": "سیشن درست ہے تک",
  "After that, sign in again while online.": "اس کے بعد آن لائن ہو کر دوبارہ لاگ اِن کریں۔",
  "Device ID": "ڈیوائس آئی ڈی",
  "This account is linked to this device. To move it to another phone or change the password, call": "یہ اکاؤنٹ اس ڈیوائس سے جڑا ہے۔ دوسرے فون پر لے جانے یا پاس ورڈ بدلنے کے لیے کال کریں",
  "App & data": "ایپ اور ڈیٹا",
  "Version": "ورژن",
  "used": "استعمال شدہ",
  "storage persistent": "اسٹوریج مستقل",
  "storage best-effort": "اسٹوریج عارضی ہو سکتا ہے",
  "Check data integrity": "ڈیٹا کی جانچ",
  "Recalculate stock": "اسٹاک دوبارہ حساب کریں",
  "Camera for barcode scanning": "بارکوڈ اسکین کے لیے کیمرہ",
  "Test camera": "کیمرہ ٹیسٹ",
  "Allowed": "اجازت ہے",
  "Blocked": "بند ہے",
  "Not asked yet": "ابھی پوچھا نہیں",
  "Unknown": "نامعلوم",
  "Camera works — read": "کیمرہ ٹھیک ہے — پڑھا",
  "On iPhone/iPad: tap Share → Add to Home Screen to install.": "آئی فون/آئی پیڈ پر: شیئر دبائیں ← Add to Home Screen۔",
  "Saved": "محفوظ ہو گیا",
  "Pharmacy name is required": "فارمیسی کا نام ضروری ہے",
  "Checking…": "جانچ ہو رہی ہے…",
  "Data integrity": "ڈیٹا کی جانچ",
  "No problems found.": "کوئی مسئلہ نہیں ملا۔",
  "Recalculating…": "دوبارہ حساب ہو رہا ہے…",
  "Corrected stock for": "اسٹاک درست کیا گیا برائے",
  "All stock quantities already match the stock ledger": "تمام اسٹاک مقداریں اسٹاک کھاتے سے مل رہی ہیں",

  // ---- backup ----
  "Your pharmacy data is stored safely on this phone/computer. Download a backup every week and keep the file in Google Drive or send it to yourself on WhatsApp, so you never lose your records.": "آپ کی فارمیسی کا ڈیٹا اسی فون/کمپیوٹر پر محفوظ ہے۔ ہر ہفتے بیک اپ ڈاؤن لوڈ کر کے گوگل ڈرائیو میں رکھیں یا خود کو واٹس ایپ پر بھیج دیں تاکہ ریکارڈ کبھی ضائع نہ ہو۔",
  "Export backup": "بیک اپ بنائیں",
  "Downloads a complete backup file: medicines, batches, customers, suppliers, sales, purchases, returns, payments, ledger and settings. Passwords are never included.": "مکمل بیک اپ فائل ڈاؤن لوڈ ہوتی ہے: ادویات، بیچ، گاہک، سپلائر، فروخت، خریداری، واپسیاں، ادائیگیاں، کھاتے اور سیٹنگز۔ پاس ورڈ کبھی شامل نہیں ہوتے۔",
  "Last backup on this device": "اس ڈیوائس پر آخری بیک اپ",
  "never": "کبھی نہیں",
  "Download backup": "بیک اپ ڈاؤن لوڈ کریں",
  "Restore backup": "بیک اپ بحال کریں",
  "Select a backup file. It is checked before anything changes; you will see its date and counts and must confirm.": "بیک اپ فائل چنیں۔ کچھ بدلنے سے پہلے اس کی جانچ ہو گی؛ آپ تاریخ اور تعداد دیکھ کر تصدیق کریں گے۔",
  "Only administrators can restore backups.": "صرف ایڈمن بیک اپ بحال کر سکتا ہے۔",
  "Backup downloaded": "بیک اپ ڈاؤن لوڈ ہو گیا",
  "Preparing backup…": "بیک اپ تیار ہو رہا ہے…",
  "Backup is valid.": "بیک اپ درست ہے۔",
  "This backup cannot be restored.": "یہ بیک اپ بحال نہیں ہو سکتا۔",
  "App": "ایپ",
  "checksum verified": "چیک سم درست",
  "Download a backup of the current data first (recommended)": "پہلے موجودہ ڈیٹا کا بیک اپ ڈاؤن لوڈ کریں (تجویز کردہ)",
  "Merge into local data": "موجودہ ڈیٹا میں ملائیں",
  "Replace all local data": "تمام ڈیٹا بدل دیں",
  "Merge adds records that are missing and updates records that are newer in the backup. Replace erases all data on this device and loads the backup.": "ملانے سے وہ ریکارڈ شامل ہوتے ہیں جو موجود نہیں اور نئے ریکارڈ اپ ڈیٹ ہوتے ہیں۔ بدلنے سے اس ڈیوائس کا تمام ڈیٹا مٹ جاتا ہے اور بیک اپ لوڈ ہوتا ہے۔",
  "This will erase all data on this device and replace it with the backup. This cannot be undone.": "یہ اس ڈیوائس کا تمام ڈیٹا مٹا کر بیک اپ سے بدل دے گا۔ یہ عمل واپس نہیں ہو سکتا۔",
  "Type REPLACE to confirm": "تصدیق کے لیے REPLACE لکھیں",
  "Records from the backup will be merged into the local data. Existing newer records are kept.": "بیک اپ کے ریکارڈ موجودہ ڈیٹا میں ملائے جائیں گے۔ موجودہ نئے ریکارڈ برقرار رہیں گے۔",
  "Replace data": "ڈیٹا بدلیں",
  "Merge": "ملائیں",
  "Replace all data?": "تمام ڈیٹا بدلیں؟",
  "Merge backup?": "بیک اپ ملائیں؟",
  "Restore cancelled: confirmation text did not match.": "بحالی منسوخ: تصدیقی لفظ نہیں ملا۔",
  "Restoring data…": "ڈیٹا بحال ہو رہا ہے…",
  "Backup restored": "بیک اپ بحال ہو گیا",
  "Merged": "ملا دیا گیا",
  "added": "شامل",
  "unchanged": "بغیر تبدیلی",
  "Merge conflicts": "ملانے میں تنازعات",
  "Batches": "بیچ",
  "Groups ": "گروپس",
  "Sale items": "فروخت کے آئٹم",
  "Purchase items": "خریداری کے آئٹم",
  "Payments / vouchers": "ادائیگیاں / واؤچر",
  "Ledger entries": "کھاتے کے اندراجات",
  "Stock movements": "اسٹاک کی حرکت",
  "Held sales ": "روکی ہوئی فروخت",
  "Activity log": "سرگرمی لاگ",
  "Counters / metadata": "کاؤنٹر / میٹا ڈیٹا",
  "Order list ": "آرڈر لسٹ",

  // ---- receipt-ish / misc ----
  "Pharmacy": "فارمیسی",
  "Medicine class ": "دوا کی قسم",
  "Total ": "کل",
  "Scan barcode": "بارکوڈ اسکین",
  "Try again": "دوبارہ کوشش کریں",
  "Add ": "شامل",
  "Please wait…": "براہِ کرم انتظار کریں…",
  "Cancel": "منسوخ",
  "Confirm": "تصدیق",
  "Please confirm": "براہِ کرم تصدیق کریں",
  "OK": "ٹھیک ہے",
  "Close": "بند کریں",
  "No matches found": "کوئی نتیجہ نہیں ملا",
  "Show more": "مزید دکھائیں",
  "Loading…": "لوڈ ہو رہا ہے…",
  "Select": "منتخب کریں",
  "Select customer": "گاہک منتخب کریں",
  "New customer": "نیا گاہک",
  "New supplier": "نیا سپلائر",
  "Search name or phone…": "نام یا فون تلاش کریں…",
};
